import React, { ButtonHTMLAttributes, MouseEventHandler } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { injected } from '../components/wallet/connectors'
import { useWeb3React } from '@web3-react/core'

// const inter = Inter({ subsets: ['latin'] })

type currencyType = {
  nep: number | string;
  busd: number | string;
}

type ActionType = {
  type: string;
  inputValue: number;
}


const reducer = (state: currencyType, action:ActionType) => {
  console.log(action)
  switch (action.type) {
    case 'nep':
       return {
        nep: action.inputValue,
        busd: action.inputValue * 3,
      }
    case 'busd' :
      return {
        busd: action.inputValue,
        nep: (action.inputValue / 3)
      }
      default: 
      return state;
  }
}

type ActiveStatusChecker = {
  isActive: boolean;
}

export const ActiveStatusChecker:React.FC<ActiveStatusChecker> = ({isActive}) => {
  if (isActive) return <p>Active</p>
  return (
    <div>Not Active</div>
  )
}


export default function Home() {
  const [state, dispatch] = React.useReducer(reducer, {nep: '', busd: ''});

  const handleInputChange = (type: string) => (e: React.ChangeEvent<HTMLInputElement>) => {
    const {value} = e.target;
    dispatch({
      type,
      inputValue: parseInt(value)
    })
  }

  const {active, account, library, connector, activate, deactivate} = useWeb3React();
  console.log({active, account, library})

  const connect = async() => {
    try {
      await activate(injected);
    } catch (error) {
      console.log(error);
    }
  }

  const handelWalletStatusCheck = (event: any) => {
    console.log(event);
    connect()
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form action="" method='POST'>
          <label htmlFor="nepali_currency">NEP</label>
          <input type="number" name="nepali_currency" onChange={handleInputChange('nep')}  value={(state.nep)} placeholder='Nepal Currency ' />

          <label htmlFor='busd_currency'>BUSD</label>
          <input type="number" name="busd_currency" onChange={handleInputChange('busd')} value={state.busd} placeholder='BUSD currency' />

          <button type='button' onClick={handelWalletStatusCheck}>Check Wallet details</button>

          <ActiveStatusChecker isActive={active} />
        </form>
      </main>
    </>
  )
}
